# Generated by Django 5.2.6 on 2025-09-17 20:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BarberShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dono', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barbearias_dono', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Barbearia',
                'verbose_name_plural': 'Barbearias',
            },
        ),
        migrations.CreateModel(
            name='BarberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('DONO', 'Dono / Admin'), ('GERENTE', 'Gerente'), ('BARBEIRO', 'Barbeiro')], default='BARBEIRO', max_length=12)),
                ('public_slug', models.SlugField(blank=True, max_length=140)),
                ('public_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('bio', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='barber_profile', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barbeiros', to='barbearias.barbershop')),
            ],
            options={
                'unique_together': {('shop', 'public_slug')},
            },
        ),
    ]
