# Generated by Django 5.2.6 on 2025-09-17 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barbershop',
            options={'ordering': ['nome']},
        ),
        migrations.RemoveField(
            model_name='barbershop',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='barbershop',
            name='dono',
        ),
        migrations.AddField(
            model_name='barbershop',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_shops', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='barbershop',
            name='telefone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='barbershop',
            name='timezone',
            field=models.CharField(default='America/Sao_Paulo', max_length=64),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Dono'), ('MANAGER', 'Gerente'), ('BARBER', 'Barbeiro')], default='BARBER', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='barbearias.barbershop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'shop')},
            },
        ),
        migrations.DeleteModel(
            name='BarberProfile',
        ),
    ]
