# Generated by Django 5.2.6 on 2025-10-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0002_accessevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbershop',
            name='api_key',
            field=models.CharField(blank=True, help_text='Chave de API fornecida pelo cliente/serviço externo.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='barbershop',
            name='instance',
            field=models.CharField(blank=True, db_index=True, help_text='Identificador externo da instância (ex.: provedor/whatsapp).', max_length=120, null=True),
        ),
    ]
