# Generated by Django 5.2.6 on 2025-09-13 14:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('duracao_min', models.PositiveIntegerField(default=30)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telefone', models.CharField(db_index=True, max_length=20)),
                ('nome', models.CharField(blank=True, max_length=120, null=True)),
                ('servico', models.CharField(max_length=120)),
                ('inicio', models.DateTimeField(blank=True, null=True)),
                ('fim', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADA', 'Confirmada'), ('NEGADA', 'Negada')], default='PENDENTE', max_length=10)),
                ('id_externo', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('callback_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['status', 'criado_em'], name='solicitacoe_status_31530a_idx'), models.Index(fields=['telefone'], name='solicitacoe_telefon_31ad77_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('status', 'CONFIRMADA'), _negated=True), ('inicio__isnull', False), _connector='OR'), name='solic_confirmada_tem_inicio')],
            },
        ),
    ]
