# Generated by Django 5.2.6 on 2025-09-22 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barbearias', '0001_initial'),
        ('clientes', '0001_initial'),
        ('servicos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico_nome', models.CharField(blank=True, max_length=120)),
                ('preco_cotado', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('duracao_min_cotada', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('inicio', models.DateTimeField(blank=True, null=True)),
                ('fim', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(blank=True, max_length=120)),
                ('telefone', models.CharField(blank=True, max_length=32)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADA', 'Confirmada'), ('NEGADA', 'Negada'), ('REALIZADA', 'Realizada')], default='PENDENTE', max_length=10)),
                ('id_externo', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('callback_url', models.URLField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barbeiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes', to='clientes.cliente')),
                ('servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes', to='servicos.servico')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='barbearias.barbershop')),
            ],
            options={
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['status', 'criado_em'], name='solicitacoe_status_31530a_idx'), models.Index(fields=['telefone'], name='solicitacoe_telefon_31ad77_idx'), models.Index(fields=['servico'], name='solicitacoe_servico_fa1d91_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('status', 'CONFIRMADA'), _negated=True), ('inicio__isnull', False), _connector='OR'), name='solic_confirmada_tem_inicio')],
            },
        ),
    ]
