# Generated by Django 5.2.6 on 2025-09-15 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='preco_cotado',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='servico_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes', to='solicitacoes.servico'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADA', 'Confirmada'), ('NEGADA', 'Negada'), ('REALIZADA', 'Realizada')], default='PENDENTE', max_length=10),
        ),
        migrations.AddIndex(
            model_name='solicitacao',
            index=models.Index(fields=['servico'], name='solicitacoe_servico_d69372_idx'),
        ),
    ]
