# Generated by Django 5.2.6 on 2025-09-24 01:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0001_initial'),
        ('clientes', '0001_initial'),
        ('servicos', '0001_initial'),
        ('solicitacoes', '0002_alter_solicitacao_id_externo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='solicitacao',
            name='solicitacoe_status_31530a_idx',
        ),
        migrations.RemoveIndex(
            model_name='solicitacao',
            name='solicitacoe_telefon_31ad77_idx',
        ),
        migrations.RemoveIndex(
            model_name='solicitacao',
            name='solicitacoe_servico_fa1d91_idx',
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='id_externo',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AddIndex(
            model_name='solicitacao',
            index=models.Index(fields=['shop', 'status', 'criado_em'], name='solicitacoe_shop_id_bad045_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitacao',
            index=models.Index(fields=['shop', 'telefone'], name='solicitacoe_shop_id_c0989f_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitacao',
            index=models.Index(fields=['shop', 'servico'], name='solicitacoe_shop_id_ae239a_idx'),
        ),
        migrations.AddConstraint(
            model_name='solicitacao',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('id_externo__isnull', True), _negated=True), models.Q(('id_externo', ''), _negated=True)), fields=('shop', 'id_externo'), name='uniq_solicitacao_por_shop_idexterno'),
        ),
    ]
