# Generated by Django 5.2.6 on 2025-09-15 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0002_solicitacao_preco_cotado_solicitacao_servico_ref_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='barbeiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes', to=settings.AUTH_USER_MODEL),
        ),
    ]
