# Generated by Django 5.2.6 on 2025-09-15 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_historicoitem_preco_tabela_and_more'),
        ('solicitacoes', '0003_solicitacao_barbeiro'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='solicitacao',
            new_name='solicitacoe_servico_fa1d91_idx',
            old_name='solicitacoe_servico_d69372_idx',
        ),
        migrations.RemoveField(
            model_name='solicitacao',
            name='servico_ref',
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='duracao_min_cotada',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='servico_nome',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='nome',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='preco_cotado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes', to='solicitacoes.servico'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='telefone',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
