# Generated by Django 5.2.6 on 2025-09-16 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0004_alter_servico_options_and_more'),
        ('solicitacoes', '0004_rename_solicitacoe_servico_d69372_idx_solicitacoe_servico_fa1d91_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes', to='servicos.servico'),
        ),
        migrations.DeleteModel(
            name='Servico',
        ),
    ]
