# Generated by Django 5.2.6 on 2025-09-17 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0001_initial'),
        ('solicitacoes', '0005_alter_solicitacao_servico_delete_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='barbearia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes', to='barbearias.barbershop'),
        ),
    ]
