# Generated by Django 5.2.6 on 2025-09-22 12:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barbearias', '0001_initial'),
        ('clientes', '0001_initial'),
        ('servicos', '0001_initial'),
        ('solicitacoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nome', models.CharField(blank=True, max_length=120)),
                ('servico_nome', models.CharField(blank=True, max_length=120)),
                ('preco_cobrado', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
                ('status', models.CharField(choices=[('CONFIRMADO', 'Confirmado'), ('PENDENTE', 'Pendente'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=10)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barbeiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to='clientes.cliente')),
                ('servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to='servicos.servico')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='barbearias.barbershop')),
                ('solicitacao', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agendamento', to='solicitacoes.solicitacao')),
            ],
            options={
                'ordering': ['inicio'],
                'indexes': [models.Index(fields=['inicio'], name='agendamento_inicio_dc8ee7_idx'), models.Index(fields=['status'], name='agendamento_status_24d1a6_idx'), models.Index(fields=['barbeiro', 'inicio'], name='agendamento_barbeir_d9a108_idx'), models.Index(fields=['cliente', 'inicio'], name='agendamento_cliente_899e5b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('fim__gt', models.F('inicio'))), name='ag_fim_gt_inicio')],
            },
        ),
        migrations.CreateModel(
            name='BarbeiroAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sábado'), (6, 'Domingo')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_minutes', models.PositiveSmallIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('lunch_start', models.TimeField(blank=True, null=True)),
                ('lunch_end', models.TimeField(blank=True, null=True)),
                ('barbeiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avail_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['barbeiro', 'weekday'],
                'constraints': [models.UniqueConstraint(fields=('barbeiro', 'weekday'), name='unique_availability_per_barbeiro_weekday'), models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='avail_end_gt_start')],
            },
        ),
        migrations.CreateModel(
            name='BarbeiroTimeOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('reason', models.CharField(blank=True, max_length=140)),
                ('barbeiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_offs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start'],
                'indexes': [models.Index(fields=['barbeiro', 'start'], name='agendamento_barbeir_fd1235_idx'), models.Index(fields=['barbeiro', 'end'], name='agendamento_barbeir_5fad1a_idx')],
            },
        ),
    ]
