# Generated by Django 5.2.6 on 2025-09-13 14:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nome', models.CharField(max_length=120)),
                ('servico_nome', models.CharField(max_length=120)),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
                ('status', models.CharField(choices=[('CONFIRMADO', 'Confirmado'), ('PENDENTE', 'Pendente'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=10)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to='clientes.cliente')),
            ],
            options={
                'ordering': ['inicio'],
                'indexes': [models.Index(fields=['inicio'], name='agendamento_inicio_dc8ee7_idx'), models.Index(fields=['status'], name='agendamento_status_24d1a6_idx')],
            },
        ),
    ]
