# Generated by Django 5.2.6 on 2025-09-23 21:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='fim',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='barbeirotimeoff',
            constraint=models.CheckConstraint(condition=models.Q(('end__gt', models.F('start'))), name='timeoff_end_gt_start'),
        ),
    ]
