# Generated by Django 5.2.6 on 2025-09-15 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_barbertimeoff_barberavailability'),
        ('clientes', '0002_historicoitem_preco_tabela_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='barberavailability',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='barber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='agendamento',
            index=models.Index(fields=['barber', 'inicio'], name='agendamento_barber__2ce064_idx'),
        ),
        migrations.AddIndex(
            model_name='barbertimeoff',
            index=models.Index(fields=['barber', 'start'], name='agendamento_barber__1b8a83_idx'),
        ),
        migrations.AddIndex(
            model_name='barbertimeoff',
            index=models.Index(fields=['barber', 'end'], name='agendamento_barber__cc799e_idx'),
        ),
        migrations.AddConstraint(
            model_name='agendamento',
            constraint=models.CheckConstraint(condition=models.Q(('fim__gt', models.F('inicio'))), name='ag_fim_gt_inicio'),
        ),
        migrations.AddConstraint(
            model_name='barberavailability',
            constraint=models.UniqueConstraint(fields=('barber', 'weekday'), name='unique_availability_per_barber_weekday'),
        ),
        migrations.AddConstraint(
            model_name='barberavailability',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='avail_end_gt_start'),
        ),
        migrations.AddConstraint(
            model_name='barbertimeoff',
            constraint=models.CheckConstraint(condition=models.Q(('end__gt', models.F('start'))), name='timeoff_end_gt_start'),
        ),
    ]
