# Generated by Django 5.2.6 on 2025-09-24 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_alter_agendamento_fim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado'), ('REALIZADO', 'Realizado')], default='CONFIRMADO', max_length=10),
        ),
    ]
