# Generated by Django 5.2.6 on 2025-09-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0003_alter_barberavailability_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barberavailability',
            name='lunch_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='barberavailability',
            name='lunch_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
