# Generated by Django 5.2.6 on 2025-09-30 23:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0003_alter_agendamento_status'),
        ('barbearias', '0001_initial'),
        ('clientes', '0001_initial'),
        ('servicos', '0001_initial'),
        ('solicitacoes', '0003_remove_solicitacao_solicitacoe_status_31530a_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='agendamento',
            name='ag_fim_gt_inicio',
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado'), ('FINALIZADO', 'Finalizado'), ('NO_SHOW', 'No-show'), ('REALIZADO', 'Realizado')], default='CONFIRMADO', max_length=20),
        ),
        migrations.AddIndex(
            model_name='agendamento',
            index=models.Index(fields=['shop', 'inicio'], name='agendamento_shop_id_c0930b_idx'),
        ),
        migrations.AddConstraint(
            model_name='agendamento',
            constraint=models.CheckConstraint(condition=models.Q(('fim__isnull', True), ('fim__gt', models.F('inicio')), _connector='OR'), name='ag_fim_gt_inicio_or_null'),
        ),
    ]
