# Generated by Django 5.2.6 on 2025-09-30 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0004_remove_agendamento_ag_fim_gt_inicio_and_more'),
        ('solicitacoes', '0003_remove_solicitacao_solicitacoe_status_31530a_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='solicitacao',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamento', to='solicitacoes.solicitacao'),
        ),
    ]
