# Generated by Django 5.2.6 on 2025-09-15 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0004_barberavailability_lunch_end_and_more'),
        ('clientes', '0002_historicoitem_preco_tabela_and_more'),
        ('servicos', '0002_alter_servico_options_alter_servico_duracao_min_and_more'),
        ('solicitacoes', '0004_rename_solicitacoe_servico_d69372_idx_solicitacoe_servico_fa1d91_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barberavailability',
            options={'ordering': ['barbeiro', 'weekday']},
        ),
        migrations.RemoveConstraint(
            model_name='barberavailability',
            name='unique_availability_per_barber_weekday',
        ),
        migrations.RemoveIndex(
            model_name='agendamento',
            name='agendamento_barber__2ce064_idx',
        ),
        migrations.RemoveIndex(
            model_name='barbertimeoff',
            name='agendamento_barber__1b8a83_idx',
        ),
        migrations.RemoveIndex(
            model_name='barbertimeoff',
            name='agendamento_barber__cc799e_idx',
        ),
        migrations.RenameField(
            model_name='barberavailability',
            old_name='barber',
            new_name='barbeiro',
        ),
        migrations.RenameField(
            model_name='barbertimeoff',
            old_name='barber',
            new_name='barbeiro',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='barber',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='barbeiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='preco_cobrado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to='servicos.servico'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='solicitacao',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agendamento', to='solicitacoes.solicitacao'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='cliente_nome',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='servico_nome',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddIndex(
            model_name='agendamento',
            index=models.Index(fields=['barbeiro', 'inicio'], name='agendamento_barbeir_d9a108_idx'),
        ),
        migrations.AddIndex(
            model_name='agendamento',
            index=models.Index(fields=['cliente', 'inicio'], name='agendamento_cliente_899e5b_idx'),
        ),
        migrations.AddIndex(
            model_name='barbertimeoff',
            index=models.Index(fields=['barbeiro', 'start'], name='agendamento_barbeir_3ba95d_idx'),
        ),
        migrations.AddIndex(
            model_name='barbertimeoff',
            index=models.Index(fields=['barbeiro', 'end'], name='agendamento_barbeir_b487c7_idx'),
        ),
        migrations.AddConstraint(
            model_name='barberavailability',
            constraint=models.UniqueConstraint(fields=('barbeiro', 'weekday'), name='unique_availability_per_barber_weekday'),
        ),
    ]
