# Generated by Django 5.2.6 on 2025-09-15 23:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0005_alter_barberavailability_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BarberAvailability',
            new_name='BarbeiroAvailability',
        ),
        migrations.RenameModel(
            old_name='BarberTimeOff',
            new_name='BarbeiroTimeOff',
        ),
        migrations.RemoveConstraint(
            model_name='barbeiroavailability',
            name='unique_availability_per_barber_weekday',
        ),
        migrations.RemoveConstraint(
            model_name='barbeirotimeoff',
            name='timeoff_end_gt_start',
        ),
        migrations.RenameIndex(
            model_name='barbeirotimeoff',
            new_name='agendamento_barbeir_fd1235_idx',
            old_name='agendamento_barbeir_3ba95d_idx',
        ),
        migrations.RenameIndex(
            model_name='barbeirotimeoff',
            new_name='agendamento_barbeir_5fad1a_idx',
            old_name='agendamento_barbeir_b487c7_idx',
        ),
        migrations.AddConstraint(
            model_name='barbeiroavailability',
            constraint=models.UniqueConstraint(fields=('barbeiro', 'weekday'), name='unique_availability_per_barbeiro_weekday'),
        ),
    ]
