# Generated by Django 5.2.6 on 2025-09-15 14:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('categoria', models.CharField(choices=[('corte', 'Corte'), ('barba', 'Barba'), ('combo', 'Combo'), ('quimica', 'Química/Coloração'), ('add_on', 'Serviços adicionais')], default='corte', max_length=20)),
                ('preco', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('duracao_min', models.PositiveIntegerField(default=30)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['nome'], name='servicos_se_nome_66baf7_idx')],
            },
        ),
    ]
