# Generated by Django 5.2.6 on 2025-09-15 22:09

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servico',
            options={'ordering': ['nome'], 'verbose_name': 'Serviço', 'verbose_name_plural': 'Serviços'},
        ),
        migrations.AlterField(
            model_name='servico',
            name='duracao_min',
            field=models.PositiveIntegerField(default=30, help_text='Duração padrão em minutos.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='servico',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Preço de tabela atual.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddIndex(
            model_name='servico',
            index=models.Index(fields=['ativo'], name='servicos_se_ativo_c22d66_idx'),
        ),
        migrations.AddIndex(
            model_name='servico',
            index=models.Index(fields=['categoria'], name='servicos_se_categor_712e68_idx'),
        ),
        migrations.AddConstraint(
            model_name='servico',
            constraint=models.CheckConstraint(condition=models.Q(('preco__gte', 0)), name='servico_preco_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='servico',
            constraint=models.CheckConstraint(condition=models.Q(('duracao_min__gt', 0)), name='servico_duracao_min_positiva'),
        ),
    ]
