# Generated by Django 5.2.6 on 2025-09-15 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_alter_servico_options_alter_servico_duracao_min_and_more'),
        ('servicos', '0002_seed_iniciais'),
    ]

    operations = [
    ]
