# Generated by Django 5.2.6 on 2025-09-15 23:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_merge_20250915_2303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servico',
            options={'ordering': ['nome']},
        ),
        migrations.RemoveConstraint(
            model_name='servico',
            name='servico_preco_nao_negativo',
        ),
        migrations.RemoveConstraint(
            model_name='servico',
            name='servico_duracao_min_positiva',
        ),
        migrations.RemoveIndex(
            model_name='servico',
            name='servicos_se_ativo_c22d66_idx',
        ),
        migrations.RemoveIndex(
            model_name='servico',
            name='servicos_se_categor_712e68_idx',
        ),
        migrations.AlterField(
            model_name='servico',
            name='duracao_min',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='servico',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
    ]
