# Generated by Django 5.2.6 on 2025-09-17 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0001_initial'),
        ('servicos', '0004_alter_servico_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='barbearias.barbershop'),
        ),
    ]
