# Generated by Django 5.2.6 on 2025-09-13 14:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('preferencias', models.TextField(blank=True, null=True)),
                ('recorrencia_status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=10)),
                ('ultimo_corte', models.DateTimeField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('barbeiro_preferido', models.CharField(blank=True, max_length=120, null=True)),
                ('foto_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['nome'], name='clientes_cl_nome_b2cdde_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistoricoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('servico', models.CharField(max_length=120)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('faltou', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='clientes.cliente')),
            ],
            options={
                'ordering': ['-data'],
                'indexes': [models.Index(fields=['cliente', 'data'], name='clientes_hi_cliente_53803c_idx')],
            },
        ),
    ]
