# Generated by Django 5.2.6 on 2025-09-22 12:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barbearias', '0001_initial'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('preferencias', models.TextField(blank=True, null=True)),
                ('recorrencia_status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=10)),
                ('ultimo_corte', models.DateTimeField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('barbeiro_preferido', models.CharField(blank=True, max_length=120, null=True)),
                ('foto_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='barbearias.barbershop')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('servico', models.CharField(max_length=120)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preco_tabela', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('faltou', models.BooleanField(default=False)),
                ('profissional', models.CharField(blank=True, max_length=120, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='clientes.cliente')),
                ('servico_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens', to='servicos.servico')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['nome'], name='clientes_cl_nome_b2cdde_idx'),
        ),
        migrations.AddIndex(
            model_name='historicoitem',
            index=models.Index(fields=['cliente', 'data'], name='clientes_hi_cliente_53803c_idx'),
        ),
        migrations.AddIndex(
            model_name='historicoitem',
            index=models.Index(fields=['servico'], name='clientes_hi_servico_7f9d95_idx'),
        ),
        migrations.AddIndex(
            model_name='historicoitem',
            index=models.Index(fields=['faltou'], name='clientes_hi_faltou_14316a_idx'),
        ),
    ]
