# Generated by Django 5.2.6 on 2025-10-02 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0002_accessevent'),
        ('clientes', '0001_initial'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoitem',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='barbearias.barbershop'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='historicoitem',
            index=models.Index(fields=['shop', 'data'], name='clientes_hi_shop_id_1b0726_idx'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('telefone__isnull', True), _negated=True), models.Q(('telefone', ''), _negated=True)), fields=('shop', 'telefone'), name='uniq_cliente_por_shop_telefone'),
        ),
    ]
