# Generated by Django 5.2.6 on 2025-09-15 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoitem',
            name='preco_tabela',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicoitem',
            name='profissional',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='historicoitem',
            name='servico_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens', to='servicos.servico'),
        ),
        migrations.AddIndex(
            model_name='historicoitem',
            index=models.Index(fields=['servico'], name='clientes_hi_servico_7f9d95_idx'),
        ),
        migrations.AddIndex(
            model_name='historicoitem',
            index=models.Index(fields=['faltou'], name='clientes_hi_faltou_14316a_idx'),
        ),
    ]
